M48
; DRILL file {KiCad (6.0.5)} date Sun Apr  2 11:03:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-02T11:03:23+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X38.1Y-17.78
X38.608Y-88.138
X124.968Y-88.392
X125.984Y-30.734
T0
M30
